display_name="Mario Captoss"
description="""
Smashline 2 exclusive

Do the Odyssey with this new Side Special for Mario, intended to work almost identically to Odyssey's movement! View the TIPS page in game for more info on how to control both Mario and Cappy!
"""
version="1.0"
category="Param"
authors="C#"